"""
report.py
---------
Render data/bibliography.csv into a human-browsable BIBLIOGRAPHY.md grouped by
the survey's categories, and mirror that generated list into README.md. Run
after discover.py.
"""
import csv
import os
from collections import Counter, defaultdict
from datetime import date

import yaml

from classify import FIGURE_CATEGORIES

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
CONFIG = os.path.join(ROOT, "config.yaml")

ORDER = FIGURE_CATEGORIES + ["Background"]
README_BIB_START = "<!-- BEGIN GENERATED BIBLIOGRAPHY -->"
README_BIB_END = "<!-- END GENERATED BIBLIOGRAPHY -->"


def link(r):
    t = " ".join((r.get("title") or "").split())
    doi, oid = r.get("doi", ""), r.get("openalex_id", "")
    if doi:
        return f"[{t}](https://doi.org/{doi})"
    if oid:
        return f"[{t}](https://openalex.org/{oid})"
    return t


def bibliography_lines(rows, by, n_seed, n_new, snapshot_date):
    lines = [
        "# Living Bibliography - Edge-Case Detection & Assessment for Automated Driving",
        "",
        f"**{len(rows)} studies** ({n_seed} expert-curated seed + {n_new} "
        "auto-discovered). NEW = auto-discovered; REVIEW = flagged for human "
        "review; category from the survey section (seed) or the centroid "
        "classifier (discovered), with optional LLM audit fields for borderline "
        "records.",
        "",
        f"Snapshot includes records through `{snapshot_date}`. Scientometric "
        "figures use an explicit year cutoff and currently omit records after "
        "2025.",
        "",
        "> Generated by `src/report.py`. Do not edit by hand - edit the pipeline.",
        "",
    ]
    for cls in ORDER + [c for c in by if c not in ORDER]:
        items = by.get(cls)
        if not items:
            continue
        lines.append(f"## {cls}  ({len(items)})\n")
        for r in sorted(items, key=lambda r: str(r.get("year")), reverse=True):
            tags = ""
            if r.get("source") == "auto-discovered":
                tags += " NEW"
            if str(r.get("needs_review")) == "True":
                tags += " REVIEW"
            lines.append(f"- ({str(r.get('year',''))[:4]}) {link(r)}{tags}")
        lines.append("")
    return lines


def readme_intro():
    return [
        "# AV Edge-Case Survey",
        "",
        "A living companion repository for the survey *Edge Cases in Automated "
        "Driving: A Survey of Detection and Assessment Methods*.",
        "",
        "This repository keeps the survey bibliography reproducible and current. "
        "It starts from the expert-curated papers used in the manuscript, "
        "searches OpenAlex for recent automated-driving edge-case literature, "
        "screens candidates with calibrated embedding-based relevance gates, "
        "assigns them to the survey taxonomy, and appends at most five new "
        "papers during each scheduled monthly update.",
        "",
        "The automation is meant to support transparent literature discovery, not "
        "to replace expert judgement. Borderline records remain flagged for human "
        "review, and the full scored candidate table is kept for auditing.",
        "",
        "For the detailed workflow, figures, tuning parameters, and reproducibility "
        "notes, see [METHODOLOGY.md](METHODOLOGY.md). The standalone generated "
        "bibliography is also kept in [BIBLIOGRAPHY.md](BIBLIOGRAPHY.md).",
        "",
        "## Repository Contents",
        "",
        "- [BIBLIOGRAPHY.md](BIBLIOGRAPHY.md): generated bibliography grouped by category.",
        "- [METHODOLOGY.md](METHODOLOGY.md): detailed pipeline description and figures.",
        "- [data/](data): seed corpus, discovered papers, scored candidates, and merged bibliography CSV.",
        "- [src/](src): harvesting, screening, classification, reporting, and figure-generation code.",
        "- [figures/](figures): generated scientometric and PRISMA-style outputs.",
        "",
        "## Current Paper List",
        "",
        README_BIB_START,
        "",
    ]


def write_readme(bib_lines):
    # Drop the bibliography H1 inside README so the front page has one title.
    embedded = bib_lines[2:] if bib_lines and bib_lines[0].startswith("# ") else bib_lines
    generated = "\n".join([README_BIB_START, ""] + embedded + [README_BIB_END])
    readme_path = os.path.join(ROOT, "README.md")
    try:
        with open(readme_path, encoding="utf-8") as f:
            current = f.read()
    except FileNotFoundError:
        current = ""

    if README_BIB_START in current and README_BIB_END in current:
        before, rest = current.split(README_BIB_START, 1)
        _, after = rest.split(README_BIB_END, 1)
        text = before.rstrip() + "\n\n" + generated + after.rstrip() + "\n"
    else:
        text = "\n".join(readme_intro() + embedded + [README_BIB_END, ""])

    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(text)


def main():
    with open(os.path.join(DATA, "bibliography.csv"), encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    by = defaultdict(list)
    for r in rows:
        by[r.get("category") or "Background"].append(r)

    n_seed = sum(1 for r in rows if r.get("source") == "seed")
    n_new = sum(1 for r in rows if r.get("source") == "auto-discovered")
    try:
        with open(CONFIG, encoding="utf-8") as f:
            config = yaml.safe_load(f) or {}
    except FileNotFoundError:
        config = {}
    snapshot_date = config.get("max_publication_date") or date.today().isoformat()

    lines = bibliography_lines(rows, by, n_seed, n_new, snapshot_date)

    with open(os.path.join(ROOT, "BIBLIOGRAPHY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    write_readme(lines)
    dist = Counter(r.get("category") or "Background" for r in rows)
    print(f"wrote BIBLIOGRAPHY.md ({len(rows)}: {n_seed} seed + {n_new} new)")
    print("wrote README.md bibliography section")
    print("  by category:", dict(dist))


if __name__ == "__main__":
    main()
