"""
report.py
---------
Render data/bibliography.csv into a human-browsable BIBLIOGRAPHY.md grouped by
the survey's categories. Run after discover.py.
"""
import csv
import os
from collections import Counter, defaultdict

from classify import FIGURE_CATEGORIES

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")

ORDER = FIGURE_CATEGORIES + ["Background"]


def link(r):
    t, doi, oid = r["title"], r.get("doi", ""), r.get("openalex_id", "")
    if doi:
        return f"[{t}](https://doi.org/{doi})"
    if oid:
        return f"[{t}](https://openalex.org/{oid})"
    return t


def main():
    rows = list(csv.DictReader(open(os.path.join(DATA, "bibliography.csv"), encoding="utf-8")))
    by = defaultdict(list)
    for r in rows:
        by[r.get("category") or "Background"].append(r)

    n_seed = sum(1 for r in rows if r.get("source") == "seed")
    n_new = sum(1 for r in rows if r.get("source") == "auto-discovered")

    lines = [
        "# Living Bibliography — Edge-Case Detection & Assessment for Automated Driving",
        "",
        f"**{len(rows)} studies** ({n_seed} expert-curated seed + {n_new} "
        "auto-discovered). 🆕 = auto-discovered; ⚠️ = flagged for human review; "
        "category from the survey section (seed) or the centroid classifier "
        "(discovered).",
        "",
        "> Generated by `src/report.py`. Do not edit by hand — edit the pipeline.",
        "",
    ]
    for cls in ORDER + [c for c in by if c not in ORDER]:
        items = by.get(cls)
        if not items:
            continue
        lines.append(f"## {cls}  ({len(items)})\n")
        for r in sorted(items, key=lambda r: str(r.get("year")), reverse=True):
            tags = ""
            if r.get("source") == "auto-discovered":
                tags += " 🆕"
            if str(r.get("needs_review")) == "True":
                tags += " ⚠️"
            lines.append(f"- ({str(r.get('year',''))[:4]}) {link(r)}{tags}")
        lines.append("")

    with open(os.path.join(ROOT, "BIBLIOGRAPHY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    dist = Counter(r.get("category") or "Background" for r in rows)
    print(f"wrote BIBLIOGRAPHY.md ({len(rows)}: {n_seed} seed + {n_new} new)")
    print("  by category:", dict(dist))


if __name__ == "__main__":
    main()
