"""
report.py
---------
Render data/bibliography.csv into a human-browsable BIBLIOGRAPHY.md grouped by
the survey taxonomy (class -> subsection), and print summary counts.  Run after
discover.py.
"""
import csv
import os
from collections import defaultdict

from classify import TAXONOMY

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")


def link(r):
    t = r["title"]
    doi = r.get("doi", "")
    oid = r.get("openalex_id", "")
    if doi:
        return f"[{t}](https://doi.org/{doi})"
    if oid:
        return f"[{t}](https://openalex.org/{oid})"
    return t


def main():
    rows = list(csv.DictReader(open(os.path.join(DATA, "bibliography.csv"), encoding="utf-8")))
    by = defaultdict(lambda: defaultdict(list))
    for r in rows:
        by[r["class"]][r["subsection"]].append(r)

    n_seed = sum(1 for r in rows if r.get("source") == "seed")
    n_new = sum(1 for r in rows if r.get("source") == "auto-discovered")

    lines = [
        "# Living Bibliography — Edge-Case Detection & Assessment for Automated Driving",
        "",
        f"**{len(rows)} studies** ({n_seed} expert-curated seed + {n_new} "
        "auto-discovered). Auto-discovered entries are marked 🆕; entries needing "
        "a human check are marked ⚠️.",
        "",
        "> Generated by `src/report.py`. Do not edit by hand — edit the pipeline.",
        "",
    ]
    for cls in list(TAXONOMY.keys()) + [c for c in by if c not in TAXONOMY]:
        if cls not in by:
            continue
        cls_n = sum(len(v) for v in by[cls].values())
        lines.append(f"## {cls}  ({cls_n})\n")
        subs_order = list(TAXONOMY.get(cls, {}).keys())
        subs_order += [s for s in by[cls] if s not in subs_order]
        for sub in subs_order:
            items = by[cls].get(sub)
            if not items:
                continue
            lines.append(f"### {sub}  ({len(items)})\n")
            for r in sorted(items, key=lambda r: str(r.get("year")), reverse=True):
                tags = ""
                if r.get("source") == "auto-discovered":
                    tags += " 🆕"
                if str(r.get("needs_review")) == "True":
                    tags += " ⚠️"
                yr = str(r.get("year", ""))[:4]
                lines.append(f"- ({yr}) {link(r)}{tags}")
            lines.append("")

    with open(os.path.join(ROOT, "BIBLIOGRAPHY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote BIBLIOGRAPHY.md  ({len(rows)} studies: {n_seed} seed + {n_new} new)")


if __name__ == "__main__":
    main()
